# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c34c2b19f3198ce5068ab2c3b83f819b77cf32f324360363ddba2b48090acd25ff0c1215b0ea907b1b229b1119631adb63b0cad0497e60131fefae5bf6ff82ec

test:
  secret_key_base: 00e72a49dc7f77c0f9cfe08e865275fa5c17a175abd97712838813c8d75393fb594c0eca53d8b1b1063b989e78e3c28398eed70cbb93c8578ad2b328747c0729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
